#!/usr/bin/perl
use Locale::TextDomain ("frames.texi" => "TITLES/");
my ($en, $ja);
while (<>) {
	($en, $ja) = (quotemeta('@chapter Frames'), quotemeta(__ '@chapter Frames')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Creating Frames'), quotemeta(__ '@section Creating Frames')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Multiple Terminals'), quotemeta(__ '@section Multiple Terminals')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Frame Geometry'), quotemeta(__ '@section Frame Geometry')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Frame Layout'), quotemeta(__ '@subsection Frame Layout')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Frame Font'), quotemeta(__ '@subsection Frame Font')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Frame Position'), quotemeta(__ '@subsection Frame Position')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Frame Size'), quotemeta(__ '@subsection Frame Size')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Implied Frame Resizing'), quotemeta(__ '@subsection Implied Frame Resizing')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Frame Parameters'), quotemeta(__ '@section Frame Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Access to Frame Parameters'), quotemeta(__ '@subsection Access to Frame Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Initial Frame Parameters'), quotemeta(__ '@subsection Initial Frame Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Window Frame Parameters'), quotemeta(__ '@subsection Window Frame Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Basic Parameters'), quotemeta(__ '@subsubsection Basic Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Position Parameters'), quotemeta(__ '@subsubsection Position Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Size Parameters'), quotemeta(__ '@subsubsection Size Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Layout Parameters'), quotemeta(__ '@subsubsection Layout Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Buffer Parameters'), quotemeta(__ '@subsubsection Buffer Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Frame Interaction Parameters'), quotemeta(__ '@subsubsection Frame Interaction Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Mouse Dragging Parameters'), quotemeta(__ '@subsubsection Mouse Dragging Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Window Management Parameters'), quotemeta(__ '@subsubsection Window Management Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Cursor Parameters'), quotemeta(__ '@subsubsection Cursor Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Font and Color Parameters'), quotemeta(__ '@subsubsection Font and Color Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Geometry'), quotemeta(__ '@subsection Geometry')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Terminal Parameters'), quotemeta(__ '@section Terminal Parameters')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Frame Titles'), quotemeta(__ '@section Frame Titles')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Deleting Frames'), quotemeta(__ '@section Deleting Frames')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Finding All Frames'), quotemeta(__ '@section Finding All Frames')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Minibuffers and Frames'), quotemeta(__ '@section Minibuffers and Frames')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Input Focus'), quotemeta(__ '@section Input Focus')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Visibility of Frames'), quotemeta(__ '@section Visibility of Frames')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Raising, Lowering and Restacking Frames'), quotemeta(__ '@section Raising, Lowering and Restacking Frames')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Frame Configurations'), quotemeta(__ '@section Frame Configurations')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Child Frames'), quotemeta(__ '@section Child Frames')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Mouse Tracking'), quotemeta(__ '@section Mouse Tracking')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Mouse Position'), quotemeta(__ '@section Mouse Position')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Pop-Up Menus'), quotemeta(__ '@section Pop-Up Menus')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Dialog Boxes'), quotemeta(__ '@section Dialog Boxes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Pointer Shape'), quotemeta(__ '@section Pointer Shape')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Window System Selections'), quotemeta(__ '@section Window System Selections')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Drag and Drop'), quotemeta(__ '@section Drag and Drop')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Color Names'), quotemeta(__ '@section Color Names')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Text Terminal Colors'), quotemeta(__ '@section Text Terminal Colors')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section X Resources'), quotemeta(__ '@section X Resources')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Display Feature Testing'), quotemeta(__ '@section Display Feature Testing')); s/$en/$ja/;
}
print;
