#!/usr/bin/perl
use Locale::TextDomain ("modes.texi" => "TITLES/");
my ($en, $ja);
while (<>) {
	($en, $ja) = (quotemeta('@chapter Major and Minor Modes'), quotemeta(__ '@chapter Major and Minor Modes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Hooks'), quotemeta(__ '@section Hooks')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Running Hooks'), quotemeta(__ '@subsection Running Hooks')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Setting Hooks'), quotemeta(__ '@subsection Setting Hooks')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Major Modes'), quotemeta(__ '@section Major Modes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Major Mode Conventions'), quotemeta(__ '@subsection Major Mode Conventions')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection How Emacs Chooses a Major Mode'), quotemeta(__ '@subsection How Emacs Chooses a Major Mode')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Getting Help about a Major Mode'), quotemeta(__ '@subsection Getting Help about a Major Mode')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Defining Derived Modes'), quotemeta(__ '@subsection Defining Derived Modes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Basic Major Modes'), quotemeta(__ '@subsection Basic Major Modes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Mode Hooks'), quotemeta(__ '@subsection Mode Hooks')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Tabulated List mode'), quotemeta(__ '@subsection Tabulated List mode')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Generic Modes'), quotemeta(__ '@subsection Generic Modes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Major Mode Examples'), quotemeta(__ '@subsection Major Mode Examples')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Minor Modes'), quotemeta(__ '@section Minor Modes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Conventions for Writing Minor Modes'), quotemeta(__ '@subsection Conventions for Writing Minor Modes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Keymaps and Minor Modes'), quotemeta(__ '@subsection Keymaps and Minor Modes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Defining Minor Modes'), quotemeta(__ '@subsection Defining Minor Modes')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Mode Line Format'), quotemeta(__ '@section Mode Line Format')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Mode Line Basics'), quotemeta(__ '@subsection Mode Line Basics')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection The Data Structure of the Mode Line'), quotemeta(__ '@subsection The Data Structure of the Mode Line')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection The Top Level of Mode Line Control'), quotemeta(__ '@subsection The Top Level of Mode Line Control')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Variables Used in the Mode Line'), quotemeta(__ '@subsection Variables Used in the Mode Line')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection @code{%}-Constructs in the Mode Line'), quotemeta(__ '@subsection @code{%}-Constructs in the Mode Line')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Properties in the Mode Line'), quotemeta(__ '@subsection Properties in the Mode Line')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Window Header Lines'), quotemeta(__ '@subsection Window Header Lines')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Emulating Mode Line Formatting'), quotemeta(__ '@subsection Emulating Mode Line Formatting')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Imenu'), quotemeta(__ '@section Imenu')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Font Lock Mode'), quotemeta(__ '@section Font Lock Mode')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Font Lock Basics'), quotemeta(__ '@subsection Font Lock Basics')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Search-based Fontification'), quotemeta(__ '@subsection Search-based Fontification')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Customizing Search-Based Fontification'), quotemeta(__ '@subsection Customizing Search-Based Fontification')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Other Font Lock Variables'), quotemeta(__ '@subsection Other Font Lock Variables')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Levels of Font Lock'), quotemeta(__ '@subsection Levels of Font Lock')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Precalculated Fontification'), quotemeta(__ '@subsection Precalculated Fontification')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Faces for Font Lock'), quotemeta(__ '@subsection Faces for Font Lock')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Syntactic Font Lock'), quotemeta(__ '@subsection Syntactic Font Lock')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Multiline Font Lock Constructs'), quotemeta(__ '@subsection Multiline Font Lock Constructs')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Font Lock Multiline'), quotemeta(__ '@subsubsection Font Lock Multiline')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Region to Fontify after a Buffer Change'), quotemeta(__ '@subsubsection Region to Fontify after a Buffer Change')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Automatic Indentation of code'), quotemeta(__ '@section Automatic Indentation of code')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Simple Minded Indentation Engine'), quotemeta(__ '@subsection Simple Minded Indentation Engine')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection SMIE Setup and Features'), quotemeta(__ '@subsubsection SMIE Setup and Features')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Operator Precedence Grammars'), quotemeta(__ '@subsubsection Operator Precedence Grammars')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Defining the Grammar of a Language'), quotemeta(__ '@subsubsection Defining the Grammar of a Language')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Defining Tokens'), quotemeta(__ '@subsubsection Defining Tokens')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Living With a Weak Parser'), quotemeta(__ '@subsubsection Living With a Weak Parser')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Specifying Indentation Rules'), quotemeta(__ '@subsubsection Specifying Indentation Rules')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Helper Functions for Indentation Rules'), quotemeta(__ '@subsubsection Helper Functions for Indentation Rules')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Sample Indentation Rules'), quotemeta(__ '@subsubsection Sample Indentation Rules')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Customizing Indentation'), quotemeta(__ '@subsubsection Customizing Indentation')); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Desktop Save Mode'), quotemeta(__ '@section Desktop Save Mode')); s/$en/$ja/;
}
print;
